# Generated by Django 6.0.2 on 2026-03-01 12:40

from django.db import migrations
from datetime import date

def add_data(apps, schema_editor):
    User = apps.get_model('backend', 'User')
    Post = apps.get_model('backend', 'Post')
    Comment = apps.get_model('backend', 'Comment')
    obj_u = User.objects.create(name='Я', birthday=date.today())
    obj_u2 = User.objects.create(name='Не я', birthday = date.today())
    obj_p = Post.objects.create(post='Новый супер пост', user_id=obj_u)
    Comment.objects.create(post='Круто!', user_id=obj_u2, from_comment_id=obj_p)


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_data)
    ]
